version: '3.1'

services:
  proxy:
      build: ./docker/proxy
      depends_on:
        - m_server
        - www_server
      ports:
        - 80:80
        - 443:443
      restart: always

  m_server:
    image: webdevops/php-apache:alpine
    volumes:
      - ./test_sites/m:/app
    restart: always
    environment:
      WEB_ALIAS_DOMAIN: m.bh3721.com
      TZ: Asia/Shanghai
      PHP_DATE_TIMEZONE: Asia/Shanghai
      XDEBUG_REMOTE_CONNECT_BACK: 0
      XDEBUG_REMOTE_HOST: host.docker.internal
      XDEBUG_REMOTE_AUTOSTART: 1

  www_server:
      image: webdevops/php-apache:alpine
      volumes:
        - ./test_sites/w:/app
        - ./docker/ssl/Apache/www.bh3721.com_ssl.crt:/opt/docker/etc/httpd/ssl/server.crt
        - ./docker/ssl/Apache/www.bh3721.com_ssl.key:/opt/docker/etc/httpd/ssl/server.key
        - ./docker/ssl/Apache/www.bh3721.com_chain.crt:/opt/docker/etc/httpd/ssl/server_chain.crt
        - ./docker/vhost.ssl.conf:/opt/docker/etc/httpd/vhost.ssl.conf
      restart: always
      logging:
        driver: "json-file"
        options:
           max-size: "50m"
           max-file: "3"
      environment:
        WEB_ALIAS_DOMAIN: www.bh3721.com
        TZ: Asia/Shanghai
        PHP_DATE_TIMEZONE: Asia/Shanghai
        WEB_DOCUMENT_ROOT: /app
        #XDEBUG_REMOTE_CONNECT_BACK: 0
        #XDEBUG_REMOTE_HOST: host.docker.internal
        #XDEBUG_REMOTE_AUTOSTART: 1
